//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inward_Register
    {
        public decimal InwardNumber { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReceivedOn { get; set; }
        [DataType(DataType.Date)]
        public DateTime LetterDated { get; set; }
        public string ReceivedFrom { get; set; }
        public string Subject { get; set; }
        public string FromAddress { get; set; }
        public string FromDistrict { get; set; }
        public string FromState { get; set; }
        public string FromCountry { get; set; }
        public string ReplyFor { get; set; }
        public string ReplyDetails { get; set; }
        public string BrowseFile { get; set; }
        public string Status { get; set; }
        public string Users { get; set; }
        public string Status1 { get; set; }
    }
}
